### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by BlackIQ** [wwwAlireza/CMS#1]
Hi,

Your project is good but there are some parts missed. You can have a toggle button for dark and light mode. Your font can be better. Current font is not bad but suggest you to use **IranSans** font. This font is not free and you have to pay for it. But I give you free. You can download it from [this link](https://github.com/BlackIQ/cdn.BlackIQ.ir/blob/main/docs/fa.BlackIQ.ir/font/iransans/iransans.ttf).

Nothing else. Theme and font. Great.

Regards.
Amirhossein.

**Comment by wwwAlireza** [comment]
Hi Amirhossein.
Thanks for your valuable feedback.
Changes will take effect soon
